idf_component_register(SRCS 
                    "globals.cpp"
                    "framebuffer.cpp"
                    "application.cpp"
                    "wrench.cpp"
                    "main.cpp"
                    "bitmaps.cpp"
                    "gui.cpp" 
                    "wrench.cpp"
                    "application.cpp"
                    "syscalls.cpp"
                    INCLUDE_DIRS ".")